version: '3'
services:
  skynet-prod-discord-bot:
    image: 'skynetdiscordbot:latest'
    environment:
      MY_SQL_HOST: "0.0.0.0"
      MY_SQL_PORT: 3306
      MY_SQL_DB: "dbname"
      MY_SQL_USER: "user"
      MY_SQL_PASSWORD: "PassWord"
    volumes:
      - ./config.yml:/usr/app/src/config.yml